// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

console.log('Vite env check:', import.meta.env)
console.log('Supabase URL:', import.meta.env.VITE_SUPABASE_URL)
console.log('Supabase key:', import.meta.env.VITE_SUPABASE_ANON_KEY)

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(
  import.meta.env.VITE_SUPABASE_URL,
  import.meta.env.VITE_SUPABASE_ANON_KEY,  {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});